
# TensorFlow 2 Exercises for Basic Tensor Manipulation

This notebook provides a set of exercises designed to familiarize you with the basics of tensor manipulation in TensorFlow 2,
which is essential for handling Large Language Models (LLMs).

## Contents
1. Tensor Basics
2. Tensor Operations
3. Manipulating Tensor Shapes
4. Indexing and Slicing
5. Broadcasting
6. Data Loading and Preprocessing

Each section will include a brief explanation followed by practical exercises.



## 1. Tensor Basics

**Objective**: Understand how to create tensors, and learn about their types and shapes.

**Exercises**:
1. Create a scalar tensor (0-D tensor) with a specific value.
2. Create a 1-D tensor (vector) with 5 elements.
3. Create a 2-D tensor (matrix) of shape (3, 3).
4. Find the data type (`dtype`) of the tensors created above.
5. Convert a numpy array to a TensorFlow tensor.


In [1]:
# prompt: Create a scalar tensor (0-D tensor) with a specific value

import tensorflow as tf

# Exercise 1: Create a scalar tensor
scalar_tensor = tf.constant(10)
print("Scalar Tensor:", scalar_tensor)

Scalar Tensor: tf.Tensor(10, shape=(), dtype=int32)


In [2]:
# prompt: Create a 1-D tensor (vector) with 5 elements

# Exercise 2: Create a 1-D tensor (vector) with 5 elements
vector_tensor = tf.constant([1, 2, 3, 4, 5])
print("Vector Tensor:", vector_tensor)

Vector Tensor: tf.Tensor([1 2 3 4 5], shape=(5,), dtype=int32)


In [3]:
# prompt: Create a 2-D tensor (matrix) of shape (3, 3) with random integers

# Exercise 3: Create a 2-D tensor (matrix) of shape (3, 3)
matrix_tensor = tf.random.uniform(shape=(3, 3), minval=0, maxval=10, dtype=tf.int32)
print("Matrix Tensor:\n", matrix_tensor)

Matrix Tensor:
 tf.Tensor(
[[7 6 2]
 [3 2 2]
 [2 7 2]], shape=(3, 3), dtype=int32)


In [4]:
# prompt: Convert a numpy array to a TensorFlow tensor

import numpy as np

# Exercise 5: Convert a numpy array to a TensorFlow tensor
numpy_array = np.array([[1, 2], [3, 4]])
tensor_from_numpy = tf.convert_to_tensor(numpy_array)
print("Tensor from NumPy array:\n", tensor_from_numpy)

Tensor from NumPy array:
 tf.Tensor(
[[1 2]
 [3 4]], shape=(2, 2), dtype=int64)



## 2. Tensor Operations

**Objective**: Perform basic arithmetic operations and learn some advanced operations.

**Exercises**:
1. Add, subtract, multiply, and divide two tensors.
2. Compute the mean and standard deviation of a tensor.
3. Apply a non-linear activation function (like ReLU) to a tensor.
4. Perform matrix multiplication between two 2-D tensors.


In [5]:
# prompt: Add, subtract, multiply, and divide two tensors

# Exercise 1: Add, subtract, multiply, and divide two tensors
tensor_a = tf.constant([[1, 2], [3, 4]], dtype=tf.float32)
tensor_b = tf.constant([[5, 6], [7, 8]], dtype=tf.float32)

tensor_add = tf.add(tensor_a, tensor_b)
tensor_subtract = tf.subtract(tensor_a, tensor_b)
tensor_multiply = tf.multiply(tensor_a, tensor_b)
tensor_divide = tf.divide(tensor_a, tensor_b)

print("\nTensor A:\n", tensor_a)
print("Tensor B:\n", tensor_b)
print("Tensor Add:\n", tensor_add)
print("Tensor Subtract:\n", tensor_subtract)
print("Tensor Multiply:\n", tensor_multiply)
print("Tensor Divide:\n", tensor_divide)


Tensor A:
 tf.Tensor(
[[1. 2.]
 [3. 4.]], shape=(2, 2), dtype=float32)
Tensor B:
 tf.Tensor(
[[5. 6.]
 [7. 8.]], shape=(2, 2), dtype=float32)
Tensor Add:
 tf.Tensor(
[[ 6.  8.]
 [10. 12.]], shape=(2, 2), dtype=float32)
Tensor Subtract:
 tf.Tensor(
[[-4. -4.]
 [-4. -4.]], shape=(2, 2), dtype=float32)
Tensor Multiply:
 tf.Tensor(
[[ 5. 12.]
 [21. 32.]], shape=(2, 2), dtype=float32)
Tensor Divide:
 tf.Tensor(
[[0.2        0.33333334]
 [0.42857143 0.5       ]], shape=(2, 2), dtype=float32)


In [8]:
# prompt: Compute the mean and standard deviation of a tensor

# Exercise 2: Compute the mean and standard deviation of a tensor
tensor_c = tf.constant([[1.0, 2.0, 3.0], [4.0, 5.0, 6.0]])
mean_c = tf.reduce_mean(tensor_c)
stddev_c = tf.math.reduce_std(tensor_c)

print("\nTensor C:\n", tensor_c)
print("Mean of Tensor C:", mean_c.numpy())
print("Standard Deviation of Tensor C:", stddev_c.numpy())


Tensor C:
 tf.Tensor(
[[1. 2. 3.]
 [4. 5. 6.]], shape=(2, 3), dtype=float32)
Mean of Tensor C: 3.5
Standard Deviation of Tensor C: 1.7078252


In [10]:
# prompt: what is the datatype of stddev_c?

print(type(stddev_c.numpy()))


<class 'numpy.float32'>


In [11]:
# prompt: Apply a non-linear activation function (like ReLU) to a tensor

# Exercise 3: Apply a non-linear activation function (like ReLU) to a tensor
tensor_d = tf.constant([[-1.0, 0.5, -2.0], [3.0, -0.5, 1.0]])
relu_tensor_d = tf.nn.relu(tensor_d)

print("\nTensor D:\n", tensor_d)
print("ReLU applied to Tensor D:\n", relu_tensor_d)


Tensor D:
 tf.Tensor(
[[-1.   0.5 -2. ]
 [ 3.  -0.5  1. ]], shape=(2, 3), dtype=float32)
ReLU applied to Tensor D:
 tf.Tensor(
[[0.  0.5 0. ]
 [3.  0.  1. ]], shape=(2, 3), dtype=float32)


In [12]:
# prompt: Perform matrix multiplication between two 2-D tensors

# Exercise 4: Perform matrix multiplication between two 2-D tensors
tensor_e = tf.constant([[1, 2], [3, 4]])
tensor_f = tf.constant([[5, 6], [7, 8]])

matrix_multiply = tf.matmul(tensor_e, tensor_f)

print("\nTensor E:\n", tensor_e)
print("Tensor F:\n", tensor_f)
print("Matrix Multiplication (E @ F):\n", matrix_multiply)


Tensor E:
 tf.Tensor(
[[1 2]
 [3 4]], shape=(2, 2), dtype=int32)
Tensor F:
 tf.Tensor(
[[5 6]
 [7 8]], shape=(2, 2), dtype=int32)
Matrix Multiplication (E @ F):
 tf.Tensor(
[[19 22]
 [43 50]], shape=(2, 2), dtype=int32)



## 3. Manipulating Tensor Shapes

**Objective**: Learn how to reshape and transpose tensors.

**Exercises**:
1. Create a tensor of shape (4, 4), then reshape it to (2, 8).
2. Transpose a 2-D tensor.
3. Flatten a 3-D tensor to a 1-D tensor.


In [13]:
# prompt: Create a tensor of shape (4, 4), then reshape it to (2, 8)

# Exercise 1: Create a tensor of shape (4, 4), then reshape it to (2, 8)
tensor_4x4 = tf.random.uniform(shape=(4, 4), minval=0, maxval=10, dtype=tf.int32)
tensor_2x8 = tf.reshape(tensor_4x4, (2, 8))

print("\nOriginal Tensor (4x4):\n", tensor_4x4)
print("Reshaped Tensor (2x8):\n", tensor_2x8)


Original Tensor (4x4):
 tf.Tensor(
[[1 5 7 0]
 [3 0 8 1]
 [2 4 3 5]
 [0 1 0 1]], shape=(4, 4), dtype=int32)
Reshaped Tensor (2x8):
 tf.Tensor(
[[1 5 7 0 3 0 8 1]
 [2 4 3 5 0 1 0 1]], shape=(2, 8), dtype=int32)



## 4. Indexing and Slicing

**Objective**: Access specific elements or slices of a tensor.

**Exercises**:
1. Extract a specific element from a tensor.
2. Slice a portion of a tensor.
3. Use boolean tensor indexing to filter elements.



## 5. Broadcasting

**Objective**: Understand and apply broadcasting rules in tensor operations.

**Exercises**:
1. Perform an element-wise addition between tensors of different shapes.
2. Broadcast a smaller tensor to match the shape of a larger tensor in an operation.


## 6. Data Loading and Preprocessing

**Objective**: Use `tf.data` for efficient data handling.

**Exercises**:
1. Create a simple dataset using `tf.data.Dataset`.
2. Apply a transformation (like mapping) to the dataset.
3. Batch and shuffle the dataset.
